apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: graph-kubernetes
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: 'true'
    labels:
      name: graph-kubernetes
    name: graph-kubernetes
    namespace: default
  rules:
    - apiGroups:
        - ''
      resources: ['*']
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - extensions
      resources: ['*']
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - apps
      resources: ['*']
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - batch
      resources: ['*']
      verbs:
        - get
        - list
        - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    labels:
      name: graph-kubernetes
    name: graph-kubernetes
  subjects:
    - kind: ServiceAccount
      name: graph-kubernetes
      namespace: default
  roleRef:
    kind: ClusterRole
    name: graph-kubernetes
    apiGroup: rbac.authorization.k8s.io
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: fluent-bit-agent-conf
    labels:
      app: fluent-bit
      component: fluent-bit-agent-conf
  data:
    fluent-bit: |
      [SERVICE]
          Parsers_File ./parsers.conf
          Grace 15
      [INPUT]
          Name tail
          Path /var/log/containers/graph-kubernetes*.log
          Exclude_Path /var/log/containers/*otel-collector*.log
          Parser cri
          Tag kube.*
          Mem_Buf_Limit 5MB
      [OUTPUT]
          Name  forward
          Host  0.0.0.0
          Port  8006
          Match *
    parsers: |
      [PARSER]
          Name        jupiter_one
          Format      json
          Time_Key    time
          Time_Format %Y-%m-%dT%H:%M:%S.%LZ
          Time_Keep   On
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: otel-agent-conf
    labels:
      app: opentelemetry
      component: otel-agent-conf
  data:
    otel-agent-config: |
      receivers:
        hostmetrics:
          collection_interval: 10s
          scrapers:
            cpu:
            load:
            memory:
            disk:
            filesystem:
            network:
            paging:
            processes:
        otlp:
          protocols:
            grpc:
            http:
        fluentforward:
          endpoint: 0.0.0.0:8006

      processors:
        batch:
        memory_limiter:
          limit_mib: 400
          spike_limit_mib: 100
          check_interval: 5s

      exporters:
        logging:
          loglevel: debug
          sampling_initial: 5
          sampling_thereafter: 200

      extensions:
        memory_ballast:
          size_mib: 165

      service:
        pipelines:
          logs:
            receivers: [fluentforward]
            processors: [memory_limiter, batch]
            exporters: [logging]
          metrics:
            receivers: [hostmetrics]
            processors: [memory_limiter, batch]
            exporters: [logging]
          traces:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [logging]
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: graph-kubernetes
  spec:
    template:
      spec:
        serviceAccountName: graph-kubernetes
        backoffLimit: 4
        initContainers:
          - name: kubexit
            image: cortexlabs/kubexit:0.40.0
            command: ['cp']
            args: ['/bin/kubexit', '/kubexit/kubexit']
            volumeMounts:
              - mountPath: /kubexit
                name: kubexit
        containers:
          - name: graph-kubernetes
            image: graph-kubernetes
            imagePullPolicy: IfNotPresent
            command: ['/kubexit/kubexit', 'yarn']
            args: ['collect']
            env:
              - name: KUBEXIT_NAME
                value: graph-kubernetes
              - name: KUBEXIT_GRAVEYARD
                value: /graveyard
              - name: KUBEXIT_BIRTH_DEPS
                value: fluent-bit,otel-collector
              - name: KUBEXIT_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: KUBEXIT_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: JUPITERONE_DEV
                value: 'true'
              - name: ACCESS_TYPE
                value: 'cluster'
              - name: NAMESPACE
                value: 'default'
              - name: LOAD_KUBERNETES_CONFIG_FROM_DEFAULT
                value: 'false'
              - name: JUPITERONE_ACCOUNT_ID
                valueFrom:
                  secretKeyRef:
                    name: graph-kubernetes
                    key: jupiteroneAccountId
              - name: JUPITERONE_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: graph-kubernetes
                    key: jupiteroneApiKey
              - name: INTEGRATION_INSTANCE_ID
                valueFrom:
                  secretKeyRef:
                    name: graph-kubernetes
                    key: jupiteroneIntegrationInstanceId
            volumeMounts:
              - mountPath: /graveyard
                name: graveyard
              - mountPath: /kubexit
                name: kubexit
          - name: otel-collector
            image: otel/opentelemetry-collector-contrib:0.33.0
            imagePullPolicy: IfNotPresent
            command: ['/kubexit/kubexit', '/otelcontribcol']
            args: ['--config=/conf/otel-agent-config.yaml']
            env:
              - name: KUBEXIT_NAME
                value: otel-collector
              - name: KUBEXIT_GRAVEYARD
                value: /graveyard
              - name: KUBEXIT_DEATH_DEPS
                value: fluent-bit
              - name: KUBEXIT_BIRTH_DEPS
                value: fluent-bit
              - name: KUBEXIT_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: KUBEXIT_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            volumeMounts:
              - name: otel-agent-config-vol
                mountPath: /conf
              - mountPath: /graveyard
                name: graveyard
              - mountPath: /kubexit
                name: kubexit
          - name: fluent-bit
            image: fluent/fluent-bit:1.8
            imagePullPolicy: IfNotPresent
            command: ['/kubexit/kubexit', '/fluent-bit/bin/fluent-bit']
            args: ['--config=/fluent-bit/etc/fluent-bit.conf']
            env:
              - name: KUBEXIT_NAME
                value: fluent-bit
              - name: KUBEXIT_GRAVEYARD
                value: /graveyard
              - name: KUBEXIT_DEATH_DEPS
                value: graph-kubernetes
            volumeMounts:
              - name: log-storage
                mountPath: /mnt/log/
                readOnly: true
              - name: fluent-bit-agent-config-vol
                mountPath: /fluent-bit/etc/
              - mountPath: /graveyard
                name: graveyard
              - mountPath: /kubexit
                name: kubexit
              - name: varlog
                mountPath: /var/log
                readOnly: true
              - name: varlibdockercontainers
                mountPath: /var/lib/docker/containers
                readOnly: true
        restartPolicy: Never
        terminationGracePeriodSeconds: 10
        volumes:
          - name: fluent-bit-agent-config-vol
            configMap:
              name: fluent-bit-agent-conf
              items:
                - key: fluent-bit
                  path: fluent-bit.conf
                - key: parsers
                  path: parsers.conf
          - name: otel-agent-config-vol
            configMap:
              name: otel-agent-conf
              items:
                - key: otel-agent-config
                  path: otel-agent-config.yaml
          - name: graveyard
            emptyDir:
              medium: Memory
          - name: kubexit
            emptyDir: {}
          - name: log-storage
            emptyDir: {}
          - name: varlog
            hostPath:
              path: /var/log
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
